window:
  dimensions:
    columns: 80
    lines: 24
  padding:
    x: 25
    y: 25
scrolling:
  multiplier: 1

font:
  normal:
    family: Source Code Variable 
    style: Medium
  bold:
    family: Source Code Variable 
    style: Bold
  italic:
    family: Source Code Variable 
    style: Italic
  bold_italic:
    family: Source Code Variable 
    style: Bold Italic
  size: 10.0

#background_opacity: 0.85
